name: flutter_3r
description: Three Rings wall board.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  backstreets_widgets: ^0.8.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_riverpod: ^2.3.9
  json_annotation: ^4.6.0
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
